version: '3.8'

services:
  mongo:
    container_name: mongo-dev
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
      - MONGO_INITDB_DATABASE=library
    ports:
      - 27017:27017
    networks:
      - mongo-me-network
    volumes:
      - /mongodb:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - mongo-me-network
    depends_on:
      - mongo

volumes:
  db:
    driver: local

networks:
  mongo-me-network:
    driver: bridge